spring:
  datasource:
    url: jdbc:sqlserver://demoservermain.database.windows.net:1433;database=newbusbookdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: rachit
    password: patani@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect

server:
  port: 8080
